### PR TITLE
Basic support for php 7 return types

### PR DESCRIPTION
**Pull request by deadbabe**

### CODE REVIEW

**Comment by POPSuL** [comment]
Can you write tests for this changes?

**Comment by POPSuL** [comment]
Great! I like it!

But, maybe you can move this array https://github.com/POPSuL/PHP-Token-Reflection/pull/1/files#diff-4559d6bc2570f8a37bf643f64ee79f04R428 to dataprovider (https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.data-providers)?

And why you loss diacritic in https://github.com/POPSuL/PHP-Token-Reflection/pull/1/files#diff-4559d6bc2570f8a37bf643f64ee79f04L12? Originals copyrigths should must as they were.

**Comment by deadbabe** [comment]
Looks ok now, finally )

**Comment by POPSuL** [comment]
@deadbabe great! Thanks!

**Pull request merged**
